### PR TITLE
[WIP] Switch from travisci to github actions for tests.

### PR DESCRIPTION
**Pull request by JeffreyThiessen**

### CODE REVIEW

**Comment by JeffreyThiessen** [comment]
I have unit tests working but the integration tests are failing locally and on the cloud.

The build list is really janky in the current state and it might be worthwhile to rewrite the tests to use a simple python virtualenv instead of the current bulky strategy of downloading and preparing from conda, as this would allow for a cleaner testing setup for github-actions too.

**Comment by ericenns** [comment]
You can change `source activate $CONDA_ENV` in .ci/install_deps.sh to `. $WORKSPACE/miniconda/bin/activate $CONDA_ENV`. The other option is to change it to `conda activate $CONDA_ENV`, but that will only work on conda 4.6 and later.

See https://github.com/phac-nml/irida-galaxy-importer/pull/24/checks?check_run_id=1519564740#step:9:132 for activate error

**Comment by JeffreyThiessen** [comment]
@ericenns this is now failing at the point we expect it to. I think it should be good for a squash and merge after you review.

**Review by ericenns — APPROVED** [review]
👍 Thanks for getting this working @JeffreyThiessen

**Pull request merged**
